backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: "content"
    label: "Website Content"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.json"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "text"}
          - {label: "Company Name", name: "company_name", widget: "string"}
